### ISSUE TITLE
preUpdate/postUpdate listener stop working

### ISSUE THREAD

**Issue by Viktor-Bredihin** [DamienHarper/auditor-bundle#248] opened 2021-02-19 13:24 UTC
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.1.0
| PHP version                 | 7.4.12
| Database                    | MySQL / PostgreSQL / SQLite / Other

#### Summary

bundle removes listeners
#### Current behavior
preUpdate/postUpdate event listeners not working after bundle enabled (dh_auditor: enabled: true)

#### How to reproduce
Add preUpdate/postUpdate listener to any entity while audit bundle is enabled

#### Expected behavior
preUpdate/postUpdate listeners should work
this row of code causing the problem
![Screenshot from 2021-02-19 16-07-56](https://user-images.githubusercontent.com/2298048/108509909-e96d0e80-72ce-11eb-8cf4-a4202f60cf5d.png)

**Comment by DamienHarper** [comment] 2021-02-19 15:41
@Viktor-Bredihin that's very weird because the line you are referencing here is only used in tests

**Comment by Viktor-Bredihin** [comment] 2021-02-19 15:46
@DamienHarper 
I'm afraid it's not

**Comment by DamienHarper** [comment] 2021-02-20 22:05
@Viktor-Bredihin well I can't reproduce the issue: both `preUpdate` and `postUpdate` are fired properly with latest stable release and the code you outline above is not loaded/executed outside of tests (you can try/use the [auditor-bundle-demo](https://github.com/DamienHarper/auditor-bundle-demo) as a sandbox for example). 
I suppose you probably have something wrong in your project (you may have used/referenced the `EntityManagerInterfaceTrait` in your code for example).

**Comment by DamienHarper** [comment] 2021-02-26 00:06
@Viktor-Bredihin any news?

**Comment by Viktor-Bredihin** [comment] 2021-02-26 08:53
@DamienHarper 
this bundle is definitely causing problems with listeners, for example as soon as I set up it, even if I make it enabled: false in dh_auditor.yaml - prePersist/postPersist listeners stop working (with cascade persist)

**Comment by DamienHarper** [comment] 2021-02-26 10:28
@Viktor-Bredihin my concern is that I can't reproduce your issue, listeners are fired properly on several of projects I have access to :/
Could you share a project that reproduce the issue with me please? It would really help ;)

**Comment by Viktor-Bredihin** [comment] 2021-02-26 12:27
@DamienHarper 
Thank you very much for support, right now I'm searching for the problem. I think you are right and the reason should be in my project, after some research I think the problem could come from api platform bundle. I will update you today

**Comment by Viktor-Bredihin** [comment] 2021-02-26 13:20
@DamienHarper 
security.yaml->firewalls->listeners in anonymous endpoints stop working
firm_registration:
        pattern:  ^/api/firms/registration
        stateless: true
        anonymous: true

**Comment by DamienHarper** [comment] 2021-02-26 13:56
@Viktor-Bredihin well, I don't get why the bundle would alter listeners of those anonymous endpoints tbh 🤔

**Comment by Viktor-Bredihin** [comment] 2021-02-27 15:19
@DamienHarper 
I found out that the problem appears only in dev/test environments, production works fine. Any idea?

**Comment by DamienHarper** [comment] 2021-03-03 09:44
@Viktor-Bredihin I'm sorry but I still don't have any idea about this behavior that still seems bound to your project

**Comment by Alexandr-Du** [comment] 2021-03-03 12:22
Hi guys, I have the same problem. I noticed that when using the metadata_cache_driver doctrine by default, there is a problem. Listeners stop working. But if you set metadata_cache_driver in the doctrine settings, for example, as shown in the picture, then the listeners work correctly.
![image](https://user-images.githubusercontent.com/79269926/109804179-055ba300-7c33-11eb-8457-6edb903a6e4f.png)

Maybe this information will be useful.

**Comment by DamienHarper** [comment] 2021-03-04 20:04
@Viktor-Bredihin I added a simple CRUD to the demo app (https://github.com/DamienHarper/auditor-bundle-demo) of the bundle and implemented a simple postUpdate listener to check if it works as expected. 
The postUpdate listener only sets a flash message indicating it's been triggered.

To check by yourself, clone the demo repository then follow its README (setup database, load fixtures, start server)
You can then:
1. browse to https://127.0.0.1:8000/author to display a list of authors
2. edit any of the authors and change its email and/or full name
3. click on save
=> You are then redirected to the list of author and the flash message is shown above the list if the postUpdate listener has been triggered. It works for me on both dev and prod environments.

Could you try and report if this works on your side?

**Comment by DamienHarper** [comment] 2021-03-11 20:49
@Viktor-Bredihin @Alexandr-Du any news?

**Comment by DamienHarper** [comment] 2021-03-18 11:37
@Viktor-Bredihin @Alexandr-Du Do you still face this issue?

**Comment by Viktor-Bredihin** [comment] 2021-03-18 11:45
@DamienHarper 
thanks for you support. I still has this issue, I have found out it's happening only for free routes (IS_AUTHENTICATED_ANONYMOUSLY), I don't have much free routes, so just replaced entity_listener with event_listener for them to avoid cache issues. Works fine now

**Comment by DamienHarper** [comment] 2021-03-18 11:49
@Viktor-Bredihin Thanks for the feedback. 
FYI there are only "free routes" in the demo example I provided. Maybe you could clone it and compare it with your project/install your project deps etc and find when it starts to misbehave.

**Comment by Viktor-Bredihin** [comment] 2021-03-18 11:59
@DamienHarper 
it's a huge project with a lot of dependencies, so going to take some time. For now I'm gonna go with event listeners for free routes

**Comment by DamienHarper** [comment] 2021-04-26 20:28
I close this issue since no further feedback has been provided and I still have no way to reproduce it. Feel free to reopen it if needed.

**Closed by DamienHarper** 2021-04-26 20:28 UTC
Labels: bug
