### ISSUE TITLE
auditor Bundle listener not call in prod and dev

### ISSUE THREAD

**Issue by zisson** [DamienHarper/auditor-bundle#251] opened 2021-03-06 11:11 UTC
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.1.0
| PHP version                 | 7.1
| Database                    | MySQL

#### Summary

After installation and configuration of the bundle, no activity on the audited entity. After some research, I had to configure the doctrine listener in the service to listen to the events.
In principle, the bundle must do this by itself. No need to do it manually

#### Current behavior

No activity on my audited entity

#### How to reproduce

Follow the installation recommended in the bundle doc and modify a header to be audited

#### Expected behavior

Pour y remedier j'ai du ajouter ces lignes dans mon fichier service.yml

 DH\Auditor\Provider\Doctrine\Auditing\Transaction\TransactionManager:
    arguments: [ '@DH\Auditor\Provider\Doctrine\DoctrineProvider' ]

  DH\Auditor\Provider\Doctrine\Auditing\Event\DoctrineSubscriber:
    arguments: [ '@DH\Auditor\Provider\Doctrine\Auditing\Transaction\TransactionManager' ]
    tags:
      - { name: doctrine.event_subscriber }

**Comment by DamienHarper** [comment] 2021-03-06 11:22
@zisson thanks for the report, could you please tell me what version of `auditor` you're using 
(run `composer info | grep "auditor"` to check that). 

The latest version of `auditor` is `1.2.0` so if you're not using the latest version, please consider updating to `1.2.0`, it should fix your issue.

**Comment by zisson** [comment] 2021-03-06 11:26
Thanks for your quick return.
I use the version ''dev-master' de auditor.

**Comment by DamienHarper** [comment] 2021-03-06 11:28
@zisson Could you please provide the result of `composer info`, it would be helpful.

**Comment by zisson** [comment] 2021-03-06 11:32
result of command 
`damienharper/auditor                 dev-master 297c37a The missing audit l...
damienharper/auditor-bundle          4.1.0              Integrate auditor l`

**Comment by DamienHarper** [comment] 2021-03-06 14:54
Could you please give the full result of `composer info`?

**Comment by zisson** [comment] 2021-03-06 16:47
@DamienHarper 
damienharper/auditor                 dev-master 297c37a The missing audit log library.
damienharper/auditor-bundle          4.1.0              Integrate auditor library in your Symfony projects.

**Comment by DamienHarper** [comment] 2021-03-06 16:48
I need the full result, not only the lines belonging to auditor please.
=> full result of `composer info`

**Comment by zisson** [comment] 2021-03-06 17:14
api-platform/core                    v2.2.0             The ultimate solution to create web APIs.
aws/aws-sdk-php                      3.173.18           AWS SDK for PHP - Use Amazon Web Services in your PHP project
aws/aws-sdk-php-symfony              2.2.2              A Symfony bundle for v3 of the AWS SDK for PHP
beberlei/doctrineextensions          v1.3.0             A set of extensions to Doctrine 2 that add support for additional query functions available in MySQL, Oracle, PostgreSQL and SQLite.
behat/transliterator                 v1.3.0             String transliterator
composer/package-versions-deprecated 1.11.99.1          Composer plugin that provides efficient querying for installed package versions (no runtime IO)
composer/semver                      1.7.2              Semver library that offers utilities, version constraint parsing and validation.
composer/xdebug-handler              1.4.5              Restarts a process without Xdebug.
damienharper/auditor                 dev-master 297c37a The missing audit log library.
damienharper/auditor-bundle          4.1.0              Integrate auditor library in your Symfony projects.
debril/feed-io                       v3.0.10            PHP library built to consume and serve JSONFeed / RSS / Atom feeds
debril/rss-atom-bundle               v4.3.0             RSS / Atom and JSONFeed support for Symfony
doctrine/annotations                 1.12.1             Docblock Annotations Parser
doctrine/cache                       1.10.2             PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                 1.6.7              PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      2.13.3             PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, persistence interfaces, proxies, event system and much m...
doctrine/data-fixtures               1.5.0              Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        2.12.1             Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle             1.12.13            Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.4.0              Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle    3.4.0              Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle  v1.3.2             Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1              The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   1.4.3              PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                1.4.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.1              PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  v1.8.1             Database Schema migrations using Doctrine DBAL
doctrine/orm                         2.7.5              Object-Relational-Mapper for PHP
doctrine/persistence                 1.3.8              The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                  1.2.2              The Doctrine Reflection project is a simple library used by the various Doctrine projects which adds some additional functionality on top of the reflection functionality that comes with PHP. It allows you to ge...
enqueue/sqs                          0.8.42             Message Queue Amazon SQS Transport
fig/link-util                        1.1.2              Common utility implementations for HTTP links
firebase/php-jwt                     v5.2.1             A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
friendsofphp/php-cs-fixer            v2.16.4            A tool to automatically fix PHP code style
friendsofsymfony/jsrouting-bundle    1.6.3              A pretty nice way to expose your Symfony2 routing to client applications.
friendsofsymfony/user-bundle         v2.0.2             Symfony FOSUserBundle
gedmo/doctrine-extensions            v2.4.42            Doctrine2 behavioral extensions
giggsey/libphonenumber-for-php       8.12.18            PHP Port of Google's libphonenumber
giggsey/locale                       1.9                Locale functions required by libphonenumber-for-php
google/apiclient                     v2.9.1             Client library for Google APIs
google/apiclient-services            v0.162.0           Client library for Google APIs
google/auth                          v1.15.0            Google Auth Library for PHP
guzzlehttp/guzzle                    6.5.5              Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.4.0              Guzzle promises library
guzzlehttp/psr7                      1.7.0              PSR-7 message implementation that also provides common utility methods
incenteev/composer-parameter-handler v2.1.4             Composer script handling your ignored parameter file
jdorn/sql-formatter                  v1.2.17            a PHP SQL highlighting library
jean85/pretty-package-versions       1.6.0              A wrapper for ocramius/package-versions to get pretty versions strings
jms/metadata                         1.7.0              Class/method/property metadata management in PHP
jms/parser-lib                       1.0.0              A library for easily creating recursive-descent parsers.
jms/serializer                       1.14.1             Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                2.4.4              Allows you to easily serialize, and deserialize data of any complexity
knplabs/gaufrette                    v0.5.0             PHP library that provides a filesystem abstraction layer
knplabs/knp-gaufrette-bundle         v0.5.3             Allows to easily use the Gaufrette library in a Symfony project
kriswallsmith/assetic                v1.4.0             Asset Management for PHP
lightsaml/lightsaml                  1.4.1              Light SAML 2.0 PHP library
lightsaml/sp-bundle                  1.2.1              Light SAML2 SP Symfony Bundle
lightsaml/symfony-bridge             1.3.0              Light SAML Symfony bridge bundle
liip/functional-test-bundle          2.0.0-alpha17      This bundles provides additional functional test-cases for Symfony applications
mandrill/mandrill                    1.0.55             API client library for the Mandrill email as a service platform
mongodb/mongodb                      1.8.0              MongoDB driver library
monolog/monolog                      1.26.0             Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/jmespath.php               2.6.0              Declaratively specify how to extract elements from a JSON document
myclabs/deep-copy                    1.10.2             Create deep copies (clones) of your objects
nelmio/cors-bundle                   1.5.6              Adds CORS (Cross-Origin Resource Sharing) headers support in your Symfony2 application
ocramius/proxy-manager               1.0.2              A library providing utilities to generate, instantiate and generally operate with Object Proxies
ovh/ovh                              v2.0.1             Wrapper for OVH APIs
ovh/php-ovh-sms                      dev-master 52d279e SDK for OVH SMS APIs
paragonie/constant_time_encoding     v2.4.0             Constant-time Implementations of RFC 4648 Encoding (Base-64, Base-32, Base-16)
paragonie/random_compat              v2.0.19            PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                     1.0.3              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                      2.0.1              Library for handling version information and constraints
php-cs-fixer/diff                    v1.3.1             sebastian/diff v2 backport support for PHP5.6
phpcollection/phpcollection          0.5.0              General-Purpose Collection Library for PHP
phpdocumentor/reflection-common      2.2.0              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    5.2.2              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver          1.4.0              A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoption/phpoption                  1.7.5              Option Type for PHP
phpseclib/phpseclib                  3.0.5              PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
phpspec/prophecy                     1.12.2             Highly opinionated mocking framework for PHP 5.3+
phpstan/extension-installer          1.1.0              Composer plugin for automatic installation of PHPStan extensions
phpstan/phpstan                      0.12.80            PHPStan - PHP Static Analysis Tool
phpstan/phpstan-doctrine             0.12.32            Doctrine extensions for PHPStan
phpstan/phpstan-symfony              0.12.20            Symfony Framework extensions and rules for PHPStan
phpunit/php-code-coverage            6.1.4              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator            2.0.3              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template            1.2.1              Simple template engine.
phpunit/php-timer                    2.1.3              Utility class for timing
phpunit/php-token-stream             3.1.2              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      7.5.20             The PHP Unit Testing framework.
predis/predis                        v1.1.6             Flexible and feature-complete Redis client for PHP and HHVM
psr/cache                            1.0.1              Common interface for caching libraries
psr/container                        1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                     1.0.1              Common interface for HTTP messages
psr/link                             1.0.0              Common interfaces for HTTP links
psr/log                              1.1.3              Common interface for logging libraries
psr/simple-cache                     1.0.1              Common interfaces for simple caching
queue-interop/queue-interop          0.6.2              Promoting the interoperability of MQs objects. Based on Java JMS
ralouphie/getallheaders              3.0.3              A polyfill for getallheaders.
ramsey/uuid                          3.9.3              Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
robrichards/xmlseclibs               3.1.1              A PHP library for XML Security
sabre/uri                            2.2.1              Functions for making sense out of URIs.
sabre/vobject                        4.3.5              The VObject library for PHP allows you to easily parse and manipulate iCalendar and vCard objects
sabre/xml                            2.2.3              sabre/xml is an XML library that you may not hate.
sebastian/code-unit-reverse-lookup   1.0.2              Looks up which function or method a line of code belongs to
sebastian/comparator                 3.0.3              Provides the functionality to compare PHP values for equality
sebastian/diff                       3.0.3              Diff implementation
sebastian/environment                4.2.4              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   3.1.3              Provides the functionality to export PHP variables for visualization
sebastian/global-state               2.0.0              Snapshotting of global state
sebastian/object-enumerator          3.0.4              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector           1.1.2              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context          3.0.1              Provides functionality to recursively process PHP variables
sebastian/resource-operations        2.0.2              Provides a list of PHP built-in functions that operate on resources
sebastian/version                    2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
sensio/distribution-bundle           v5.0.25            Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.29            This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v3.1.7             This bundle generates code for you
sensiolabs/security-checker          v6.0.3             A security checker for your composer.lock
sentry/sentry                        1.11.0             A PHP client for Sentry (http://getsentry.com)
sentry/sentry-symfony                1.0.3              Symfony integration for Sentry (http://getsentry.com)
simshaun/recurr                      v2.2.3             PHP library for working with recurrence rules
snc/redis-bundle                     3.3.0              A Redis bundle for Symfony
softcreatr/jsonpath                  0.7.2              JSONPath implementation for parsing, searching and flattening arrays
stof/doctrine-extensions-bundle      v1.3.0             Integration of the gedmo/doctrine-extensions with Symfony2
swiftmailer/swiftmailer              v5.4.12            Swiftmailer, free feature-rich PHP mailer
symfony/assetic-bundle               v2.8.2             Integrates Assetic into Symfony2
symfony/deprecation-contracts        v2.2.0             A generic function and convention to trigger deprecation notices
symfony/http-client                  v5.2.3             Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts        v2.3.1             Generic abstractions related to HTTP clients
symfony/mime                         v5.2.3             Allows manipulating MIME messages
symfony/monolog-bundle               v3.6.0             Symfony MonologBundle
symfony/phpunit-bridge               v4.4.19            Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-apcu                v1.22.1            Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype               v1.22.1            Symfony polyfill for ctype functions
symfony/polyfill-intl-icu            v1.22.1            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn            v1.22.1            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer     v1.22.1            Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.22.1            Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.20.0            Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.20.0            Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72               v1.22.1            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73               v1.22.1            Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.22.1            Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/service-contracts            v2.2.0             Generic abstractions related to writing services
symfony/swiftmailer-bundle           v2.6.7             Symfony SwiftmailerBundle
symfony/symfony                      v3.4.47            The Symfony PHP framework
theseer/tokenizer                    1.2.0              A small library for converting tokenized PHP source code into XML and potentially other formats
twig/extensions                      v1.5.4             Common additional features for Twig that do not directly belong in core
twig/twig                            v2.14.3            Twig, the flexible, fast, and secure template language for PHP
vich/uploader-bundle                 1.0.0              Ease file uploads attached to entities
webmozart/assert                     1.9.1              Assertions to validate method input/output with nice error messages.
wikimedia/composer-merge-plugin      v1.4.1             Composer plugin to merge multiple composer.json files
willdurand/jsonp-callback-validator  v1.1.0             JSONP callback validator.
willdurand/negotiation               v2.3.1             Content Negotiation tools for PHP provided as a standalone library.
zendframework/zend-code              2.6.3              provides facilities to generate arbitrary code using an object oriented interface

**Comment by DamienHarper** [comment] 2021-03-06 18:13
@zisson that's strange, I don't see any ref to `symfony/doctrine-bridge`. Could you try to add it to your deps please?

**Comment by zisson** [comment] 2021-03-08 08:59
ok.
But Why doctrine-bridge is not a dependency of your bundle ?

**Comment by DamienHarper** [comment] 2021-03-08 09:30
@zisson [it is](https://github.com/DamienHarper/auditor-bundle/blob/827b1d18d189f583f39901ffef5b3d5777088d05/composer.json#L19), that's why I found your `composer info` output strange.

**Comment by DamienHarper** [comment] 2021-03-11 20:48
@zisson Any news?

**Comment by DamienHarper** [comment] 2021-03-18 11:37
@zisson Do you still face this issue?

**Comment by DamienHarper** [comment] 2021-03-23 16:15
@benoliver999 thanks for the feedback and regarding Symfony 3.4, nobody's perfect 🤣 
More seriously, I notice that you also don't have `symfony/doctrine-bridge` either which seems weird since [it's required by `auditor-bundle`](https://github.com/DamienHarper/auditor-bundle/blob/827b1d18d189f583f39901ffef5b3d5777088d05/composer.json#L19).
Could you please try to install it manually and retry?

**Comment by benoliver999** [comment] 2021-03-23 16:54
I can't get it to install directly with composer require, it moans about a 
conflict with another require.

I also tried `composer require symfony/doctrine-bridge "^3.4"`

It didn't moan, but also it weirdly didn't appear to install doctrine-bridge. 
composer show still didn't show it.

Tried removing the services anyway, but it stopped working again.

**Comment by gassan** [comment] 2021-03-28 20:14
its very strange. Local (macos) works without entries (both dev and prod) With entries in services.yml all changes are stored twice.
On live server (debian) it works only with adding services to services.yml (dev and prod)

**Comment by benoliver999** [comment] 2021-03-28 20:55
Wow, I wouldn't have tied it back to OS!

I can confirm I'm using Debian.

I really don't mind having the entries in services.yml but as you say if it 
could end up auditing stuff twice it's something to keep an eye on.

**Comment by llupa** [comment] 2021-07-05 17:37
I had this issue today. Same as the other commenters. 

In my case adding the services in my `services.yml` seems to fix the issue. I also have a Sf 3.4 project. 

My main suspicion right now is the way Sf 3.4 `symfony/symfony` works, which conflicts with Sf flex / Sf 4.4 and up.  In the Doctrine bridge library under `RegisterEventListenersAndSubscribersPass` Symfony is trying to service-ify subscribers and listeners related to Doctrine, the Auditor library directly injects the subscriber class in the EventManager from Doctrine. The hypothesis is that maybe the Auditor should let Symfony handle this and let the Doctrine EvM "alone". 🤷 

I haven't found anything substantial, but if I do I will update this comment (at least).

**Comment by gassan** [comment] 2021-08-12 08:55
Since 09.07.2021 works good on prod without lines in services.yaml. I have no idea what was changed at the time.

**Comment by DamienHarper** [comment] 2021-09-27 16:35
As long as I've never been able to reproduce the issue and no other feedback have been provided, I close this issue. Feel free to reopen if needed.

**Closed by DamienHarper** 2021-09-27 16:35 UTC
Labels: bug

**Comment by moag1000** [comment] 2022-01-18 17:49
I can confirm that this issue is happening to me on both stable and dev-master version of auditor-bundle (Symfony 5.4.2 LTS, recent apache, php8.1, recent mariadb) on a debian buster machine both on dev and prod.
The exact same project on my dev machine executes logging perfectly (same php and mariadb version), so I assume it's some weird OS behaviour. There is nothing unusual in the logs.

My fix was to register the services manually in the services.xml (but only in the debian machine to avoid double logging on the main machine).

Any advice how to track this down further? 
Unfortunately, I am not able to publish the demo because of the productive state of the machine in my case.
