### ISSUE TITLE
An auditing service named "X" is already registered.

### ISSUE THREAD

**Issue by INHack20** [DamienHarper/auditor-bundle#260] opened 2021-04-26 18:05 UTC
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.1.0
| PHP version                 | 7.2.34
| Database                    | MySQL

#### Summary

I want to audit multiple database tables and for that I put the following configuration.

#### How to reproduce

Doctrine configuration:

                                              doctrine:
                                                  dbal:
                                                      connections:
                                                          default:
                                                              # configure these for your database server
                                                              driver: 'pdo_mysql'
                                                              server_version: '5.7'
                                                              charset: utf8mb4
                                                              default_table_options:
                                                                  charset: utf8mb4
                                                                  collate: utf8mb4_unicode_ci
                                                              url: '%env(resolve:DATABASE_URL)%'
                                                          secondary:
                                                              # configure these for your database server
                                                              driver: 'pdo_mysql'
                                                              server_version: '5.7'
                                                              charset: utf8mb4
                                                              default_table_options:
                                                                  charset: utf8mb4
                                                                  collate: utf8mb4_unicode_ci
                                                              url: '%env(resolve:DATABASE_URL_SECONDARY)%'
                                              
                                                      # IMPORTANT: You MUST configure your server version,
                                                      # either here or in the DATABASE_URL env var (see .env file)
                                                      #server_version: '5.7'
                                                  orm:
                                                      auto_generate_proxy_classes: true
                                                      entity_managers:
                                                          default:
                                                              connection: default
                                                              naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                                                              default_repository_class: App\Repository\RootEntityRepository
                                                              auto_mapping: true
                                                              mappings:
                                                                  App:
                                                                      is_bundle: false
                                                                      type: annotation
                                                                      dir: '%kernel.project_dir%/src/Entity/M'
                                                                      prefix: 'App\Entity\M'
                                                                      alias: App
                                                              filters:
                                                                  basemaster:
                                                                      class: App\Service\Filter\BaseMasterFilter
                                                                      enabled: false
                                                          secondary:
                                                              connection: secondary
                                                              naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                                                              mappings:
                                                                  Customer:
                                                                      is_bundle: false
                                                                      type: annotation
                                                                      dir: '%kernel.project_dir%/src/Entity/S'
                                                                      prefix: 'App\Entity\S'
                                                                      alias: Secondary

Multiple database configuration:

        dh_auditor:
            enabled: true
            providers:
                doctrine:
                    auditing_services:
                        - '@doctrine.orm.default_entity_manager'
                        - '@doctrine.orm.secondary_entity_manager'
                    storage_services:
                        - '@doctrine.orm.secondary_entity_manager'
                    entities:
                        App\Entity\M\Incidence\Incidence: ~
                        App\Entity\M\Requirement: ~
                        App\Entity\S\ObjectManager\NoteManager\Note: ~
                        App\Entity\S\Email\Component: ~
                        App\Entity\S\Email\EmailTemplate: ~
                viewer: true
                ignored_columns:
                    - createdAt
                    - updatedAt

**Comment by DamienHarper** [comment] 2021-04-26 20:03
@INHack20 thanks for the feedback, seems a duplicate of #257

**Closed** 2021-04-26 23:14 UTC
Labels: bug

**Comment by DamienHarper** [comment] 2021-04-26 23:15
@INHack20 This should is fixed in `master` branch.

**Comment by INHack20** [comment] 2021-04-27 00:30
@DamienHarper Thanks, very good component.
I recommend that you place some configuration files for easy integration to easy_admin, which is a bundle that is being used a lot as an administrator.

**Comment by DamienHarper** [comment] 2021-04-27 06:15
@INHack20 Thanks for these kindly words :) 
Could you please elaborate on: 
> I recommend that you place some configuration files for easy integration to easy_admin
